# models/staging/sources/sources.yml
version: 2

sources:
  - name: gda_raw
    description: "Raw data source from UATRS PostgreSQL database"
    schema: uatrs_db
    database: "{{ target.database }}"  # Uses your target database
    tables:
      - name: annonce
      - name: bonanalyse
      - name: calendrier
      - name: champficheanalyse
      - name: convention
      - name: correspondance
      - name: diplome
      - name: devis
      - name: etablissementnonuniversitaire
      - name: etablissementcaractereadministratif
      - name: etablissementcaracterecommercial
      - name: ficheanalyse
      - name: equipement
      - name: faculteecole
      - name: etudiant
      - name: facturation
      - name: etablissementuniversitaire
      - name: membreexterne
      - name: laboratoire
      - name: moyenpaiement
      - name: moyenscontact
      - name: membreuatrs
      - name: secteur
      - name: history
      - name: grade
      - name: statutbonanalyse
      - name: service
      - name: statutconfirmationdemandebonanalyse
      - name: specialite
      - name: statutdemandeficheanalyse
      - name: souschampficheanalyse
      - name: statutconfirmationdemandedevis
      - name: statutcorrespondance
      - name: statutequipement
      - name: typecorrespondance
      - name: statutfaisabilitedemandebonanalyse
      - name: typechamp
      - name: statutfaisabilitedemandedevis
      - name: typeanalyse
      - name: unitemesure
      - name: typeetablissement
      - name: statutoperationanalyse
      - name: valeurproposee
      - name: users
      - name: demandeficheanalyse
      - name: detailbonanalysemoyenscontact
      - name: detailbonanalyseservice
      - name: detailbonanalyseservicestatutfaisabilite
      - name: detailbonanalysestatutconfirmation
      - name: detailchampficheanalysesouschampficheanalyse
      - name: detailchampficheanalysevaleurproposeeficheanalyse
      - name: valeurproposeeficheanalyse
      - name: detailchargedemaintenanceequipement
      - name: detailchargedemandeanalysebonanalyse
      - name: detailchargedemandeanalysedevis
      - name: dotation
      - name: detailchefdivisiondotation
      - name: detailchefserviceservice
      - name: detaildevismoyenscontact
      - name: detaildevisservice
      - name: detaildevisservicestatutfaisabilite
      - name: detaildevisstatutconfirmation
      - name: dossieranalyse
      - name: detaildossieranalyseficheanalyse
      - name: detailequipementtypeanalyse
      - name: detailfaculteecoleprofesseur
      - name: detaillaboratoireunitemesure
      - name: detailmembreexterneannonce
      - name: detailmembreuatrsannonce
      - name: detailresponsablelaboratoirelaboratoire
      - name: detailsbonanalyse
      - name: detailtypeanalyseunitemesure
      - name: detailsdevis
      - name: detailsouschampficheanalysevaleurproposeeficheanalyse
      - name: detailsficheanalyse
      - name: detailstatutcorrespondance
      - name: civilite
      - name: pays
      - name: operationanalyse
      - name: ordreanalyse
      - name: tarif
      - name: typetarif
      - name: user_authorities
